POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Manik",
  "email": "manikrb2005@gmail.com",
  "password": "1234567"
}

###


POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "laxmirb2005@gmail.com",
  "password": "123456"
}

###


GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMmZlODhmMTk5MTkwZDAzZTZkZWIzZiIsImlhdCI6MTc4MTU4MDEwNCwiZXhwIjoxNzgyMTg0OTA0fQ.6nel-taN8G24DbJ_C0FiWEVJkWD8N2lrmjn2IaDS08k


###



POST http://localhost:5000/api/workspaces
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMmZlODhmMTk5MTkwZDAzZTZkZWIzZiIsImlhdCI6MTc4MTU4MDEwNCwiZXhwIjoxNzgyMTg0OTA0fQ.6nel-taN8G24DbJ_C0FiWEVJkWD8N2lrmjn2IaDS08k

{
  "name": "My First Workspace",
  "description": "Testing CollabSpace"
}





###

POST http://localhost:5000/api/channels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMmZlODhmMTk5MTkwZDAzZTZkZWIzZiIsImlhdCI6MTc4MTU4MDEwNCwiZXhwIjoxNzgyMTg0OTA0fQ.6nel-taN8G24DbJ_C0FiWEVJkWD8N2lrmjn2IaDS08k


{
  "name": "general",
  "description": "General discussion",
  "workspaceId": "6a30c1627b29efaaaad57a96"
}